import type { PlanData, ComponentNode } from "./types.ts"

export interface ScaffoldFile {
  path: string
  content: string
}

export function generateScaffold(plan: PlanData): ScaffoldFile[] {
  return [
    { path: "package.json", content: pkg(plan) },
    { path: "tsconfig.json", content: tsconfig() },
    { path: ".gitignore", content: gitignore() },
    { path: ".env.example", content: envExample(plan) },
    { path: "src/app/globals.css", content: globalsCss() },
    { path: "src/app/layout.tsx", content: layout(plan) },
    { path: "src/app/page.tsx", content: page(plan) },
    { path: "README.md", content: readme(plan) },
    ...(needsDb(plan) ? [{ path: "prisma/schema.prisma", content: prismaSchema(plan) }] : []),
  ]
}

function needsDb(plan: PlanData): boolean {
  const db = plan.infrastructure.database ?? ""
  return db.includes("Supabase") || db.includes("PostgreSQL")
}

function pkg(plan: PlanData): string {
  const deps: Record<string, string> = { next: "*", react: "*", "react-dom": "*" }
  const devDeps: Record<string, string> = { typescript: "*", "@types/react": "*", "@types/node": "*", tailwindcss: "*" }

  const db = plan.infrastructure.database ?? ""
  const auth = plan.infrastructure.auth ?? ""

  if (db.includes("Supabase")) deps["@supabase/supabase-js"] = "*"
  if (auth.includes("NextAuth")) deps["next-auth"] = "*"
  if (auth.includes("Supabase Auth") && !auth.includes("NextAuth")) deps["@supabase/ssr"] = "*"
  if (plan.infrastructure.analytics === "PostHog") deps["posthog-js"] = "*"
  if (plan.infrastructure.emails === "Resend") deps["resend"] = "*"

  return JSON.stringify({
    name: "my-app",
    version: "0.1.0",
    private: true,
    type: "module",
    scripts: { dev: "next dev", build: "next build", start: "next start", lint: "next lint", typecheck: "tsc --noEmit" },
    dependencies: deps,
    devDependencies: devDeps,
  }, null, 2)
}

function tsconfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: "ES2022", lib: ["dom", "dom.iterable", "esnext"], module: "ESNext",
      moduleResolution: "bundler", jsx: "preserve", strict: true, noEmit: true,
      incremental: true, esModuleInterop: true, skipLibCheck: true,
      resolveJsonModule: true, isolatedModules: true,
      plugins: [{ name: "next" }], paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2)
}

function gitignore(): string {
  return "node_modules/\ndist/\n.next/\n.env\n.env.local\n.turbo/\n*.tsbuildinfo\n"
}

function envExample(plan: PlanData): string {
  const lines: string[] = [
    "# Environment Variables",
    "# Generated by ADE - " + plan.domain,
    "",
  ]
  const db = plan.infrastructure.database ?? ""
  const auth = plan.infrastructure.auth ?? ""

  if (db.includes("Supabase")) {
    lines.push("# Supabase")
    lines.push("NEXT_PUBLIC_SUPABASE_URL=your_supabase_url")
    lines.push("NEXT_PUBLIC_SUPABASE_ANON_KEY=your_supabase_anon_key")
    lines.push("")
  }
  if (auth.includes("NextAuth")) {
    lines.push("# NextAuth")
    lines.push("AUTH_SECRET=your_auth_secret")
    lines.push("AUTH_GITHUB_ID=your_github_id")
    lines.push("AUTH_GITHUB_SECRET=your_github_secret")
    lines.push("")
  }
  if (plan.infrastructure.analytics === "PostHog") {
    lines.push("# PostHog")
    lines.push("NEXT_PUBLIC_POSTHOG_KEY=your_posthog_key")
    lines.push("NEXT_PUBLIC_POSTHOG_HOST=your_posthog_host")
    lines.push("")
  }
  if (plan.infrastructure.emails === "Resend") {
    lines.push("# Resend")
    lines.push("RESEND_API_KEY=your_resend_api_key")
    lines.push("")
  }
  lines.push("# General")
  lines.push("NEXT_PUBLIC_APP_URL=http://localhost:3000")
  lines.push("NODE_ENV=development")

  return lines.join("\n")
}

function globalsCss(): string {
  return [
    '@import "tailwindcss";',
    "",
    ":root { --background: #ffffff; --foreground: #171717; }",
    "@media (prefers-color-scheme: dark) {",
    "  :root { --background: #0a0a0a; --foreground: #ededed; }",
    "}",
    "",
    "body { background: var(--background); color: var(--foreground); font-family: system-ui, sans-serif; }",
  ].join("\n")
}

function layout(plan: PlanData): string {
  return [
    'import type { Metadata } from "next"',
    "",
    "export const metadata: Metadata = {",
    '  title: "' + capitalize(plan.domain) + '",',
    '  description: "Built with ADE - ' + plan.domain + ' architecture",',
    "}",
    "",
    "export default function RootLayout({ children }: { children: React.ReactNode }) {",
    "  return (",
    '    <html lang="en">',
    "      <body>{children}</body>",
    "    </html>",
    "  )",
    "}",
  ].join("\n")
}

function page(plan: PlanData): string {
  return [
    "export default function Home() {",
    "  return (",
    '    <main className="min-h-screen p-8">',
    '      <h1 className="text-4xl font-bold mb-4">' + capitalize(plan.domain) + "</h1>",
    '      <p className="text-lg text-gray-600">',
    "        Architecture: " + plan.data.structures.join(", "),
    "      </p>",
    '      <p className="text-gray-500 mt-2">',
    "        Stack: " + plan.infrastructure.frontend + " + " + plan.infrastructure.database,
    "      </p>",
    "    </main>",
    "  )",
    "}",
  ].join("\n")
}

function readme(plan: PlanData): string {
  const lines: string[] = [
    "# " + capitalize(plan.domain),
    "",
    "## Architecture",
    "",
    "Generated by **ADE (Architecture Decision Engine)**",
    "",
    "### Stack",
    "",
    "| Layer | Choice |",
    "|-------|--------|",
    "| Frontend | " + plan.infrastructure.frontend + " |",
    "| Backend | " + plan.infrastructure.backend + " |",
    "| Database | " + (plan.infrastructure.database ?? "") + " |",
    "| Storage | " + (plan.infrastructure.storage ?? "") + " |",
    "| Auth | " + (plan.infrastructure.auth ?? "") + " |",
    "| Deploy | " + plan.infrastructure.deploy + " |",
    "| Analytics | " + plan.infrastructure.analytics + " |",
    "| Emails | " + plan.infrastructure.emails + " |",
  ]
  if (plan.infrastructure.blockchain) lines.push("| Blockchain | " + plan.infrastructure.blockchain + " |")
  if (plan.infrastructure.ai) lines.push("| AI | " + plan.infrastructure.ai + " |")
  if (plan.infrastructure.memory) lines.push("| Memory | " + plan.infrastructure.memory + " |")

  lines.push("", "### Data Structures", "")
  for (const s of plan.data.structures) lines.push("- " + s)

  lines.push("", "### Component Tree", "", "```")
  lines.push(renderTree(plan.components.tree, 0))
  lines.push("```", "", "## Getting Started", "", "```bash", "npm install", "npm run dev", "```")

  return lines.join("\n")
}

function renderTree(node: ComponentNode, depth: number): string {
  const indent = "  ".repeat(depth)
  let result = indent + node.name
  if (node.children) {
    for (const child of node.children) {
      result += "\n" + renderTree(child, depth + 1)
    }
  }
  return result
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

function prismaSchema(plan: PlanData): string {
  const models = plan.data.structures.map(s => modelFor(s)).filter(Boolean).join("\n\n")
  return [
    'generator client { provider = "prisma-client-js" }',
    "",
    'datasource db { provider = "postgresql" url = env("DATABASE_URL") }',
    "",
    models,
  ].join("\n")
}

function modelFor(s: string): string {
  const models: Record<string, string> = {
    "hash-map": [
      'model KeyValue {',
      '  id String @id @default(cuid())',
      '  key String @unique',
      '  value Json',
      '  createdAt DateTime @default(now())',
      '  updatedAt DateTime @updatedAt',
      '  @@index([key])',
      '}',
    ].join("\n"),
    graph: [
      'model Node {',
      '  id String @id @default(cuid())',
      '  label String',
      '  type String',
      '  metadata Json?',
      '  edgesFrom Edge[] @relation("FromNode")',
      '  edgesTo Edge[] @relation("ToNode")',
      '}',
      '',
      'model Edge {',
      '  id String @id @default(cuid())',
      '  fromId String',
      '  toId String',
      '  label String?',
      '  weight Float?',
      '  from Node @relation("FromNode", fields: [fromId], references: [id])',
      '  to Node @relation("ToNode", fields: [toId], references: [id])',
      '  @@index([fromId])',
      '  @@index([toId])',
      '}',
    ].join("\n"),
    tree: [
      'model TreeNode {',
      '  id String @id @default(cuid())',
      '  parentId String?',
      '  name String',
      '  slug String?',
      '  sortOrder Int @default(0)',
      '  metadata Json?',
      '  children TreeNode[] @relation("TreeHierarchy", fields: [id], references: [parentId])',
      '  parent TreeNode? @relation("TreeHierarchy", fields: [parentId], references: [id])',
      '  @@index([parentId])',
      '  @@index([slug])',
      '}',
    ].join("\n"),
  }
  return models[s] ?? ""
}
