import type {
  ProjectInput,
  SecurityAuditResult,
  SecurityCheck,
  SecurityLayer,
  SecuritySeverity,
} from "./types.ts"

interface CheckDef {
  id: string
  law: string
  layer: SecurityLayer
  title: string
  description: string
  severity: SecuritySeverity
  owasp: string
  cwe: string
  applicable: (input: Partial<ProjectInput>) => boolean
  exploit: string
  impact: string
  mitigation: string
  tests: string[]
}

const has = (v: boolean | undefined) => !!v

const LAW_DEFS: CheckDef[] = [
  {
    id: "LAW-1",
    law: "Law 1: Never Trust the Client",
    layer: "perimeter",
    title: "Mandatory server-side validation",
    description:
      "Any data coming from the frontend, mobile app, CLI or agent is hostile territory. No client-side validation replaces server-side.",
    severity: "CRITICAL",
    owasp: "A03 Injection",
    cwe: "CWE-345",
    applicable: () => true,
    exploit: "Send form data, query params or headers manipulated with role=admin, someone else's userId or injection payloads.",
    impact: "Privilege escalation, access to other users' data, unauthorized execution of operations.",
    mitigation: "Validate 100% of inputs on the backend with a typed schema (Zod). Never trust client-side validation.",
    tests: ["rejects payload with disallowed role/admin", "rejects someone else's userId when creating a resource"],
  },
  {
    id: "LAW-2",
    law: "Law 2: Restricted Schema (Mass Assignment Protection)",
    layer: "perimeter",
    title: "Whitelist of fields per endpoint",
    description:
      "Every mutation must explicitly declare the accepted fields. Extra fields are rejected or discarded.",
    severity: "HIGH",
    owasp: "A04 Insecure Design",
    cwe: "CWE-915",
    applicable: () => true,
    exploit: "Send extra fields in the body (ex: {isAdmin: true, credits: 999}) to an endpoint that accepts ...req.body.",
    impact: "Mass assignment: attacker changes privilege, balance or ownership fields they should not control.",
    mitigation: "Forbid direct input spread. Define a schema per endpoint with explicit fields.",
    tests: ["rejects payload with disallowed fields (mass assignment)"],
  },
  {
    id: "LAW-3",
    law: "Law 3: Size and Rate Limits (DoS Prevention)",
    layer: "perimeter",
    title: "Input, payload and rate limits",
    description:
      "Texts have maxLength, arrays maxItems, payloads have limits, listings have pagination with max pageSize, critical endpoints have rate limits.",
    severity: "HIGH",
    owasp: "A04 Insecure Design",
    cwe: "CWE-770",
    applicable: () => true,
    exploit: "Send giant payloads, unbounded listings (?pageSize=999999) or mass requests to exhaust resources.",
    impact: "DoS, uncontrolled storage and compute cost, full database dump.",
    mitigation: "Apply maxLength/maxItems, pagination with limits, rate limiting per IP + user + API key with graceful 429.",
    tests: ["prevents full database dump via unbounded pagination", "rejects text above maximum size"],
  },
  {
    id: "LAW-4",
    law: "Law 4: Perimeter Protection (Middleware Shield)",
    layer: "perimeter",
    title: "Security middleware mounted on routes",
    description:
      "Strict CORS, anti-CSRF on mutations, mandatory headers, parameter pollution and replay attack prevention.",
    severity: "HIGH",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-436",
    applicable: () => true,
    exploit: "Abuse permissive CORS, missing CSRF on mutations, parameter pollution (?role=admin&role=user).",
    impact: "Actions taken on behalf of an authenticated user, cross-origin access, validation bypass.",
    mitigation: "Mount security middleware explicitly (helmet, per-origin CORS, CSRF). Never define and forget to mount.",
    tests: ["security middleware mounted on critical routes", "CORS blocks disallowed origins"],
  },
  {
    id: "LAW-5",
    law: "Law 5: Identity Extracted, Never Received (IDOR/BOLA)",
    layer: "identity",
    title: "User ID from token/session",
    description:
      "userId, roles and permissions are extracted from the verified session. Never accepted as argument or query param.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-639",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "Change userId/accountId in query params or body to access another user's resources (IDOR).",
    impact: "Read/edit/delete of other users' or tenants' data.",
    mitigation: "Extract identity from ctx.auth/req.user (validated JWT, session store). Never from input.",
    tests: ["rejects access to another user's resource (IDOR)"],
  },
  {
    id: "LAW-6",
    law: "Law 6: Authorization on Every Operation",
    layer: "identity",
    title: "Auth ≠ Authorization",
    description:
      "Being logged in is not enough. Every operation verifies the required role AND explicit ownership/permission of the resource.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-862",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant) || has(i.apiAccess),
    exploit: "Access an admin route with a regular account or another user's resource passing the `if (user)` check.",
    impact: "Access to administrative functions, cross-tenant data and privileged operations.",
    mitigation: "Verify role and ownership in every operation. Admin endpoints require an explicit role.",
    tests: ["must deny access without authentication token", "blocks regular account on admin route"],
  },
  {
    id: "LAW-7",
    law: "Law 7: Row Level Security and Tenant Isolation",
    layer: "identity",
    title: "RLS enabled and policies per auth.uid()",
    description:
      "BaaS with RLS must have RLS enabled. Policies restrict SELECT/INSERT/UPDATE/DELETE by auth.uid(). Never USING (true).",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "Query without tenant/owner filter; USING (true) policy or RLS disabled to 'make it work'.",
    impact: "Cross-tenant leak, access to all users' data.",
    mitigation: "Enable RLS and create policies per auth.uid(). Forbid USING (true) in production.",
    tests: ["tenant isolation tests", "RLS policy restricts by auth.uid()"],
  },
  {
    id: "LAW-8",
    law: "Law 8: Transactional Atomicity (Race Condition)",
    layer: "business",
    title: "Atomic transactions for limited resources",
    description:
      "Balances, counters, stock, purchases and likes read state and apply the change in the same atomic transaction.",
    severity: "CRITICAL",
    owasp: "A04 Insecure Design",
    cwe: "CWE-362",
    applicable: (i) => has(i.payments) || has(i.blockchain),
    exploit: "10 simultaneous purchase/withdraw/decrement requests cause negative balance or duplication (double-spending).",
    impact: "Double-spending, duplicate refunds, multiple coupon redemptions, financial loss.",
    mitigation: "Use transactions with SELECT FOR UPDATE or atomic locks. Forbid check-then-act without a transaction.",
    tests: ["prevents race condition on simultaneous checkout", "does not allow negative balance with concurrent requests"],
  },
  {
    id: "LAW-9",
    law: "Law 9: Minimal Data Exposure",
    layer: "business",
    title: "Explicit projection in queries",
    description:
      "APIs return only the required fields. Returning full database objects, hashes, tokens, other users' emails or billing is forbidden.",
    severity: "HIGH",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-200",
    applicable: () => true,
    exploit: "Endpoint returns the whole database object including password_hash, service_role, internal ids.",
    impact: "Leak of credentials, billing data and other users' information.",
    mitigation: "Explicit select/projection. Serialize with a DTO/response schema.",
    tests: ["does not expose sensitive fields in API response"],
  },
  {
    id: "LAW-10",
    law: "Law 10: Output Sanitization (XSS/Injection)",
    layer: "business",
    title: "Escaping at render, no innerHTML",
    description:
      "Backend data rendered in the frontend is escaped by the framework. Vectors: dangerouslySetInnerHTML, v-html, innerHTML, eval.",
    severity: "HIGH",
    owasp: "A03 Injection",
    cwe: "CWE-79",
    applicable: () => true,
    exploit: "Inject <script> or malicious HTML into content rendered with dangerouslySetInnerHTML.",
    impact: "Persistent XSS, session theft, code execution in victims' browsers.",
    mitigation: "Use framework escaping. Forbid dangerouslySetInnerHTML with unsanitized data.",
    tests: ["escapes malicious HTML at render", "blocks dangerouslySetInnerHTML with external data"],
  },
  {
    id: "LAW-11",
    law: "Law 11: Secrets Never in the Bundle",
    layer: "infrastructure",
    title: "Credentials in server-side env vars",
    description:
      "No keys in client-side code, NEXT_PUBLIC_ variables, logs, error responses or committed files.",
    severity: "CRITICAL",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "API key hardcoded at the top of a client-side file, committed .env, service_role exposed to the user.",
    impact: "Full compromise of the service account, resource abuse, data leak.",
    mitigation: "Move everything to server-side env vars, rotate leaked keys, .env in .gitignore.",
    tests: ["no hardcoded secrets in the code", "keys never exposed in error responses"],
  },
  {
    id: "LAW-12",
    law: "Law 12: Zero-Trust Upload and SSRF",
    layer: "infrastructure",
    title: "Magic bytes, reprocessing and SSRF blocklist",
    description:
      "Upload validates Magic Bytes (not just extension). Fetching user-provided URLs has an allowlist and blocks internal IPs.",
    severity: "HIGH",
    owasp: "A10 SSRF",
    cwe: "CWE-918",
    applicable: (i) => has(i.upload) || has(i.webhooks) || has(i.ai),
    exploit: "Upload of a polyglot file or fetch to 169.254.169.254 (cloud metadata) / internal networks.",
    impact: "SSRF: access to the internal network and cloud metadata. Malware/polyglot upload.",
    mitigation: "Validate magic bytes, reprocess images, block private/link-local IPs on fetch.",
    tests: ["blocks SSRF via proxy to internal IP", "rejects upload with fake extension (magic bytes)"],
  },
  {
    id: "LAW-13",
    law: "Law 13: Dependency and Supply Chain Awareness",
    layer: "infrastructure",
    title: "Dependency audit and phantom packages",
    description:
      "Assess known CVEs, abandoned packages, insecure APIs (jwt.decode without verify, bcrypt rounds < 10, yaml.load).",
    severity: "HIGH",
    owasp: "A06 Vulnerable and Outdated Components",
    cwe: "CWE-1104",
    applicable: () => true,
    exploit: "Dependency with a known CVE or phantom package hallucinated by the AI agent.",
    impact: "Known remote exploitation, compromised supply chain.",
    mitigation: "npm audit/ossf-scorecard, pin versions, verify package existence with context7 before using.",
    tests: ["audits dependencies against known CVEs", "no phantom dependency in package.json"],
  },
  {
    id: "LAW-14",
    law: "Law 14: Secure and Observable Logging",
    layer: "infrastructure",
    title: "Errors with context, generic message to the client",
    description:
      "Security logs with IP, user agent, userId, timestamp, attempted action. To the client: generic message. Never log secrets.",
    severity: "MEDIUM",
    owasp: "A09 Logging Failures",
    cwe: "CWE-532",
    applicable: () => true,
    exploit: "Stack trace exposed in production or console.log of request body with credentials.",
    impact: "Leak of internals, attack assistance, invisible failures that hide vulnerabilities.",
    mitigation: "Structured logging with context; try/catch with logging and re-throw; never log passwords/tokens.",
    tests: ["error returns generic message to the client", "stack trace not exposed in production"],
  },
  {
    id: "LAW-15",
    law: "Law 15: Secure Configuration by Default",
    layer: "infrastructure",
    title: "Security headers, secure cookies, debug off",
    description:
      "HSTS, X-Content-Type-Options, X-Frame-Options, CSP. Cookies HttpOnly/Secure/SameSite. Debug and source maps off in production.",
    severity: "HIGH",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-693",
    applicable: () => true,
    exploit: "Clickjacking without X-Frame-Options, cookie without HttpOnly, debug enabled exposing data.",
    impact: "Clickjacking, session theft via XSS, exposure of debug information.",
    mitigation: "Apply security headers, HttpOnly+Secure+SameSite cookies, NODE_ENV=production.",
    tests: ["response includes mandatory security headers", "session cookie is HttpOnly and Secure"],
  },
]

const ATTACK_VECTOR_DEFS: CheckDef[] = [
  {
    id: "VECTOR-1",
    law: "Vector 1: BOLA / IDOR",
    layer: "identity",
    title: "Access to resources by mutable ID",
    description: "User A reads/edits/deletes user B's resources by changing an ID.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-639",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "GET /api/projects/123 changed to /api/projects/456 (another user's resource).",
    impact: "Access to third parties' private data.",
    mitigation: "Extract identity from the token and validate ownership on every read.",
    tests: ["rejects access to another user's resource (IDOR)"],
  },
  {
    id: "VECTOR-2",
    law: "Vector 2: Broken Access Control",
    layer: "identity",
    title: "Protected route accessible without auth",
    description: "Regular user accesses admin/mod functions; protected route without auth.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-862",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "Access /api/admin/users without a token or with a regular user token.",
    impact: "Administrative privilege escalation.",
    mitigation: "Guard every admin route (role) and in the API middleware.",
    tests: ["blocks regular account on admin route"],
  },
  {
    id: "VECTOR-3",
    law: "Vector 3: Race Conditions",
    layer: "business",
    title: "Concurrency in value operations",
    description: "Simultaneous requests on purchase/withdraw/like cause negative balance or duplication.",
    severity: "CRITICAL",
    owasp: "A04 Insecure Design",
    cwe: "CWE-362",
    applicable: (i) => has(i.payments) || has(i.blockchain),
    exploit: "User sends 10 simultaneous POST /api/orders with the same balance.",
    impact: "Double-spending and financial loss.",
    mitigation: "Atomic transaction with a lock on the record.",
    tests: ["prevents race condition on simultaneous checkout"],
  },
  {
    id: "VECTOR-4",
    law: "Vector 4: Business Logic Flaws",
    layer: "business",
    title: "Gaps in refunds, coupons, trials and referral",
    description: "Buy → withdraw commission → refund. Infinite trial usage.",
    severity: "HIGH",
    owasp: "A04 Insecure Design",
    cwe: "CWE-841",
    applicable: (i) => has(i.payments),
    exploit: "Request a refund after withdrawing commission; reuse a first-use coupon.",
    impact: "Financial loss, abuse of promotions.",
    mitigation: "Model state transitions; validate event sequences with idempotency.",
    tests: ["does not allow withdrawing commission and refunding the same purchase"],
  },
  {
    id: "VECTOR-5",
    law: "Vector 5: SSRF",
    layer: "infrastructure",
    title: "Server-side fetch of arbitrary URL",
    description: "Server-side proxy/fetch accepts user URLs reaching internal network/metadata.",
    severity: "HIGH",
    owasp: "A10 SSRF",
    cwe: "CWE-918",
    applicable: (i) => has(i.upload) || has(i.webhooks) || has(i.ai) || has(i.cms),
    exploit: "POST with url=http://169.254.169.254/latest/meta-data/ on webhook/image proxy.",
    impact: "Access to cloud metadata, internal networks and local services.",
    mitigation: "Domain allowlist; block private/link-local IPs.",
    tests: ["blocks SSRF via proxy to internal IP"],
  },
  {
    id: "VECTOR-6",
    law: "Vector 6: Injection",
    layer: "perimeter",
    title: "Input concatenation in queries/commands",
    description: "SQL/NoSQL/OS/template injection via concatenation.",
    severity: "CRITICAL",
    owasp: "A03 Injection",
    cwe: "CWE-89",
    applicable: () => true,
    exploit: "Input with ' OR 1=1-- in a concatenated query.",
    impact: "Unauthorized read/write in the database, command execution.",
    mitigation: "Mandatory parameterization; ORM with prepared queries; no template literals in SQL.",
    tests: ["rejects SQL injection payload (OR 1=1)"],
  },
  {
    id: "VECTOR-7",
    law: "Vector 7: Data Exposure",
    layer: "business",
    title: "Responses expose sensitive fields",
    description: "API returns hashes, tokens, other users' emails, billing data.",
    severity: "HIGH",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-200",
    applicable: () => true,
    exploit: "GET /api/user returns the whole database object.",
    impact: "Leak of sensitive data.",
    mitigation: "Response DTO with explicit projection.",
    tests: ["does not expose sensitive fields in API response"],
  },
  {
    id: "VECTOR-8",
    law: "Vector 8: Auth Bypass",
    layer: "identity",
    title: "Tamperable token or route without verification",
    description: "Routes without token; JWT with none algorithm/weak secret.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-287",
    applicable: (i) => has(i.auth) || has(i.sso) || has(i.apiAccess),
    exploit: "Send JWT with alg:none or forge a token with a known secret.",
    impact: "Authentication completely bypassed.",
    mitigation: "jwt.verify with strong algorithm and secret; never jwt.decode without verify.",
    tests: ["rejects JWT token with alg:none"],
  },
  {
    id: "VECTOR-9",
    law: "Vector 9: Insecure Deserialization",
    layer: "perimeter",
    title: "Deserialized payloads without schema",
    description: "Client objects deserialized without schema validation.",
    severity: "HIGH",
    owasp: "A08 Deserialization",
    cwe: "CWE-502",
    applicable: () => true,
    exploit: "JSON with malicious prototype or unexpected fields in deserialization.",
    impact: "RCE or data corruption.",
    mitigation: "Always validate with a schema (Zod) before using.",
    tests: ["rejects payload with disallowed fields (mass assignment)"],
  },
  {
    id: "VECTOR-10",
    law: "Vector 10: Secrets Leakage",
    layer: "infrastructure",
    title: "Credentials in code, logs and responses",
    description: "Secrets in commits, client-side variables, logs and error responses.",
    severity: "CRITICAL",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "npm install of a package that reads process.env; committed .env.",
    impact: "Total service compromise.",
    mitigation: "Secrets manager, rotation, CI scan.",
    tests: ["no hardcoded secrets in the code"],
  },
  {
    id: "VECTOR-11",
    law: "Vector 11: Missing RLS / Tenant Leak",
    layer: "identity",
    title: "Queries without ownership/tenant filter",
    description: "Queries without tenant/owner filter; permissive RLS.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "SELECT without WHERE tenant_id in a multi-tenant app.",
    impact: "Complete cross-tenant leak.",
    mitigation: "Mandatory tenant filter + RLS per auth.uid().",
    tests: ["tenant isolation tests"],
  },
  {
    id: "VECTOR-12",
    law: "Vector 12: Phantom Dependencies",
    layer: "infrastructure",
    title: "Packages that don't exist or have CVEs",
    description: "Imports of nonexistent (hallucinated) packages or versions with CVEs.",
    severity: "HIGH",
    owasp: "A06 Vulnerable and Outdated Components",
    cwe: "CWE-1104",
    applicable: () => true,
    exploit: "Import of a phantom package not in the registry → supply chain.",
    impact: "Broken build or compromised dependency.",
    mitigation: "Verify real package existence and docs with context7; npm audit in CI.",
    tests: ["no phantom dependency in package.json"],
  },
]

const ANTI_PATTERN_DEFS: CheckDef[] = [
  {
    id: "A1",
    law: "Anti-Pattern A1: Client-only security",
    layer: "perimeter",
    title: "Auth/validation only in the frontend",
    description: "Auth checks and validations exist only in the frontend; the backend accepts anything.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-602",
    applicable: () => true,
    exploit: "Call the API directly (curl) without going through the frontend.",
    impact: "All protections bypassed in seconds.",
    mitigation: "Replicate all validation/authorization on the server.",
    tests: ["endpoint rejects direct call without token"],
  },
  {
    id: "A2",
    law: "Anti-Pattern A2: Auth removed to 'fix a bug'",
    layer: "identity",
    title: "requireAuth() removed or bypassed",
    description: "Auth middleware, token verification try/catch or requireAuth removed to fix a runtime error.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-287",
    applicable: (i) => has(i.auth) || has(i.sso) || has(i.apiAccess),
    exploit: "Endpoint that should require login accepts anonymous requests after guard removal.",
    impact: "All users' data exposed.",
    mitigation: "Never remove auth to fix a build; use a mock/test with a valid token.",
    tests: ["must deny access without authentication token"],
  },
  {
    id: "A3",
    law: "Anti-Pattern A3: Hardcoded secrets",
    layer: "infrastructure",
    title: "API keys and service roles in the code",
    description: "Keys directly in source code, especially in client-side files.",
    severity: "CRITICAL",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "GitHub scan of a committed key.",
    impact: "Compromised service account.",
    mitigation: "Server-side env vars + rotation + secret scan in CI.",
    tests: ["no hardcoded secrets in the code"],
  },
  {
    id: "A4",
    law: "Anti-Pattern A4: RLS disabled",
    layer: "identity",
    title: "RLS disabled or USING (true) policy",
    description: "ALTER TABLE DISABLE ROW LEVEL SECURITY or USING (true) policies to 'make it work'.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "Query returns all tenants' data.",
    impact: "Total data leak.",
    mitigation: "Re-enable RLS; policies per auth.uid(); isolation tests in CI.",
    tests: ["RLS policy restricts by auth.uid()"],
  },
  {
    id: "A5",
    law: "Anti-Pattern A5: Phantom middleware",
    layer: "perimeter",
    title: "Rate limiter/CORS/CSRF imported but never mounted",
    description: "Protections configured but never registered with app.use() or equivalent.",
    severity: "HIGH",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-1188",
    applicable: () => true,
    exploit: "Endpoint without rate limit/CORS because the middleware was not mounted.",
    impact: "Endpoint abuse, DoS, open CORS.",
    mitigation: "Test that verifies middleware mounted on routes.",
    tests: ["security middleware mounted on critical routes"],
  },
  {
    id: "A6",
    law: "Anti-Pattern A6: Error swallowing",
    layer: "infrastructure",
    title: "Empty catch or console.log without handling",
    description: "catch (e) {} or console.log(e) without re-throw/adequate logging. Invisible failures.",
    severity: "MEDIUM",
    owasp: "A09 Logging Failures",
    cwe: "CWE-390",
    applicable: () => true,
    exploit: "Silenced authorization error hides attempted unauthorized access.",
    impact: "Invisible vulnerabilities in production.",
    mitigation: "Structured logging with context and re-throw when needed.",
    tests: ["error returns generic message to the client"],
  },
  {
    id: "A7",
    law: "Anti-Pattern A7: Excessive permissions",
    layer: "identity",
    title: "Service role instead of anon key; tokens without expiration",
    description: "Service role keys where anon would suffice; IAM with *; tokens without expiration.",
    severity: "HIGH",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-276",
    applicable: (i) => has(i.auth) || has(i.apiAccess) || has(i.payments),
    exploit: "Service role key used on the client exposes the whole database.",
    impact: "Unrestricted data access.",
    mitigation: "Least privilege: anon key on the client, service role only on the server.",
    tests: ["service role key never exposed to the client"],
  },
  {
    id: "A8",
    law: "Anti-Pattern A8: Missing validation in Server Actions",
    layer: "perimeter",
    title: "Server Actions/API Routes without validation",
    description: "Next.js Server Actions, Remix/SvelteKit actions without input validation (trust raw FormData).",
    severity: "HIGH",
    owasp: "A03 Injection",
    cwe: "CWE-20",
    applicable: () => true,
    exploit: "Server Action accepts manipulated FormData with extra fields.",
    impact: "Mass assignment and corrupted data.",
    mitigation: "Validate all FormData with a schema before using.",
    tests: ["Server Action rejects payload with disallowed fields"],
  },
  {
    id: "A9",
    law: "Anti-Pattern A9: Admin exposed by default",
    layer: "identity",
    title: "Admin/console panels accessible without auth",
    description: "/api/admin/* routes and debug consoles accessible without authentication in production.",
    severity: "CRITICAL",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-552",
    applicable: () => true,
    exploit: "Access /api/admin/dashboard directly.",
    impact: "Total control of the application.",
    mitigation: "Protect admin routes with role + auth by default.",
    tests: ["admin route requires administrative role"],
  },
  {
    id: "A10",
    law: "Anti-Pattern A10: Pagination without limit",
    layer: "perimeter",
    title: "SELECT * or listing without LIMIT",
    description: "Listing queries without LIMIT allow full dump via ?pageSize=999999.",
    severity: "HIGH",
    owasp: "A04 Insecure Design",
    cwe: "CWE-770",
    applicable: () => true,
    exploit: "GET /api/items?pageSize=999999 returns the whole database.",
    impact: "Full database dump.",
    mitigation: "Maximum pageSize limit and small default.",
    tests: ["prevents full database dump via unbounded pagination"],
  },
]

const severityScore: Record<SecuritySeverity, number> = {
  CRITICAL: 25,
  HIGH: 15,
  MEDIUM: 8,
  LOW: 3,
}

function evaluate(defs: CheckDef[], input: Partial<ProjectInput>): SecurityCheck[] {
  return defs.map((d) => ({
    id: d.id,
    law: d.law,
    layer: d.layer,
    title: d.title,
    description: d.description,
    severity: d.severity,
    owasp: d.owasp,
    cwe: d.cwe,
    applicable: d.applicable(input),
    exploit: d.exploit,
    impact: d.impact,
    mitigation: d.mitigation,
    tests: d.tests,
  }))
}

export function runSecurityAudit(input: Partial<ProjectInput>): SecurityAuditResult {
  const laws = evaluate(LAW_DEFS, input)
  const attackVectors = evaluate(ATTACK_VECTOR_DEFS, input)
  const antiPatterns = evaluate(ANTI_PATTERN_DEFS, input)

  const applicable = [...laws, ...attackVectors, ...antiPatterns].filter((c) => c.applicable)
  // This function receives architecture intent, not source code. Applicable
  // checks are requirements to verify, not confirmed vulnerabilities.
  const critical = 0
  const high = 0
  const medium = 0
  const low = 0
  const applicableAntiPatterns = antiPatterns.filter((c) => c.applicable).map((c) => c.id)
  const vibeAntiPatterns: string[] = []

  const ordered = [...applicable].sort(
    (a, b) => severityScore[b.severity] - severityScore[a.severity],
  )
  const topActions = ordered.slice(0, 3).map(
    (c) => `[${c.severity}] ${c.id} — ${c.title}: ${c.mitigation}`,
  )

  const redTeam = applicable
    .filter((c) => c.severity === "CRITICAL" || c.severity === "HIGH")
    .map((c) => `[${c.id}] ${c.exploit}`)
  const blueTeam = applicable.map((c) => `[${c.id}] ${c.mitigation}`)
  const securityTests = Array.from(
    new Set(applicable.flatMap((c) => c.tests)),
  ).map((t) => `test("VULN-${applicable.findIndex((c) => c.tests.includes(t)) + 1}: ${t}")`)

  return {
    target: input.description ? `${input.domain} — ${input.description.slice(0, 80)}` : `${input.domain}`,
    laws,
    attackVectors,
    antiPatterns,
    scorecard: {
      critical,
      high,
      medium,
      low,
      applicable: applicable.length,
      applicableAntiPatterns,
      vibeAntiPatterns,
      grade: "N/A",
      assessment: "design-checklist",
      summary: `${applicable.length} checks applicable; no code vulnerabilities were confirmed — assessment N/A`,
    },
    topActions,
    redTeam,
    blueTeam,
    securityTests,
  }
}
