import type {
  ProjectInput,
  SecurityAuditResult,
  SecurityCheck,
  SecurityLayer,
  SecuritySeverity,
} from "./types.ts"

interface CheckDef {
  id: string
  law: string
  layer: SecurityLayer
  title: string
  description: string
  severity: SecuritySeverity
  owasp: string
  cwe: string
  applicable: (input: Partial<ProjectInput>) => boolean
  exploit: string
  impact: string
  mitigation: string
  tests: string[]
}

const has = (v: boolean | undefined) => !!v

const LAW_DEFS: CheckDef[] = [
  {
    id: "LAW-1",
    law: "Lei 1: Nunca Confie no Cliente",
    layer: "perimeter",
    title: "Validação server-side obrigatória",
    description:
      "Qualquer dado vindo de frontend, app mobile, CLI ou agente é território hostil. Nenhuma validação client-side substitui a server-side.",
    severity: "CRITICA",
    owasp: "A03 Injection",
    cwe: "CWE-345",
    applicable: () => true,
    exploit: "Enviar form data, query params ou headers manipulados com role=admin, userId alheio ou payloads de injeção.",
    impact: "Escalação de privilégio, acesso a dados de outros usuários, execução não autorizada de operações.",
    mitigation: "Validar 100% dos inputs no backend com schema tipado (Zod). Nunca confiar em validação client-side.",
    tests: ["rejeita payload com role/admin não permitido", "rejeita userId alheio na criação de recurso"],
  },
  {
    id: "LAW-2",
    law: "Lei 2: Schema Restrito (Mass Assignment Protection)",
    layer: "perimeter",
    title: "Whitelist de campos por endpoint",
    description:
      "Toda mutação deve declarar explicitamente os campos aceitos. Campos extras são rejeitados ou descartados.",
    severity: "ALTA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-915",
    applicable: () => true,
    exploit: "Enviar campos extras no body (ex: {isAdmin: true, credits: 999}) em um endpoint que aceita ...req.body.",
    impact: "Mass assignment: atacante altera campos de privilégio, saldo ou ownership que não deveria controlar.",
    mitigation: "Proibir spread direto de input. Definir schema por endpoint com campos explícitos.",
    tests: ["rejeita payload com campos não permitidos (mass assignment)"],
  },
  {
    id: "LAW-3",
    law: "Lei 3: Limites de Tamanho e Taxa (DoS Prevention)",
    layer: "perimeter",
    title: "Limites de input, payload e rate",
    description:
      "Textos têm maxLength, arrays maxItems, payloads têm limite, listagens têm paginação com pageSize máximo, endpoints críticos têm rate limit.",
    severity: "ALTA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-770",
    applicable: () => true,
    exploit: "Enviar payloads gigantes, listagens sem limite (?pageSize=999999) ou requests em massa para esgotar recursos.",
    impact: "DoS, custo de armazenamento e computação não controlado, dump completo do banco.",
    mitigation: "Aplicar maxLength/maxItems, paginação com limite, rate limiting por IP + usuário + API key com 429 gracioso.",
    tests: ["impede dump completo via paginação sem limite", "rejeita texto acima do tamanho máximo"],
  },
  {
    id: "LAW-4",
    law: "Lei 4: Proteção de Perímetro (Middleware Shield)",
    layer: "perimeter",
    title: "Middleware de segurança montado nas rotas",
    description:
      "CORS estrito, anti-CSRF em mutações, headers obrigatórios, prevenção de parameter pollution e replay attacks.",
    severity: "ALTA",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-436",
    applicable: () => true,
    exploit: "Abusar de CORS permissivo, ausência de CSRF em mutações, parameter pollution (?role=admin&role=user).",
    impact: "Ações em nome de usuário autenticado, acesso cruzado de origem, bypass de validações.",
    mitigation: "Montar middleware de segurança explicitamente (helmet, CORS por origem, CSRF). Nunca definir e não montar.",
    tests: ["middleware de segurança montado nas rotas críticas", "CORS bloqueia origens não permitidas"],
  },
  {
    id: "LAW-5",
    law: "Lei 5: Identidade Extraída, Nunca Recebida (IDOR/BOLA)",
    layer: "identity",
    title: "ID do usuário vindo do token/sessão",
    description:
      "userId, roles e permissões são extraídos da sessão verificada. Nunca aceitos como argumento ou query param.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-639",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "Alterar userId/accountId em query params ou body para acessar recursos de outro usuário (IDOR).",
    impact: "Leitura/edição/exclusão de dados de outros usuários ou tenants.",
    mitigation: "Extrair identidade de ctx.auth/req.user (JWT validado, session store). Nunca do input.",
    tests: ["rejeita acesso a recurso de outro usuário (IDOR)"],
  },
  {
    id: "LAW-6",
    law: "Lei 6: Autorização em Cada Operação",
    layer: "identity",
    title: "Auth ≠ Autorização",
    description:
      "Estar logado não basta. Cada operação verifica role necessária E ownership/permissão explícita do recurso.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-862",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant) || has(i.apiAccess),
    exploit: "Acessar rota de admin com conta comum ou recurso de outro usuário passando no check `if (user)`.",
    impact: "Acesso a funções administrativas, dados cross-tenant e operações privilegiadas.",
    mitigation: "Verificar role e ownership em cada operação. Endpoints de admin exigem role explícita.",
    tests: ["deve negar acesso sem token de autenticação", "bloqueia conta comum em rota de admin"],
  },
  {
    id: "LAW-7",
    law: "Lei 7: Row Level Security e Tenant Isolation",
    layer: "identity",
    title: "RLS habilitado e policies por auth.uid()",
    description:
      "BaaS com RLS deve ter RLS habilitado. Policies restringem SELECT/INSERT/UPDATE/DELETE por auth.uid(). Nunca USING (true).",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "Query sem filtro de tenant/owner; policy USING (true) ou RLS desabilitado para 'fazer funcionar'.",
    impact: "Vazamento cross-tenant, acesso a dados de todos os usuários.",
    mitigation: "Habilitar RLS e criar policies por auth.uid(). Proibir USING (true) em produção.",
    tests: ["testes de isolamento entre tenants", "policy RLS restringe por auth.uid()"],
  },
  {
    id: "LAW-8",
    law: "Lei 8: Atomicidade Transacional (Race Condition)",
    layer: "business",
    title: "Transações atômicas para recursos limitados",
    description:
      "Saldos, contadores, estoque, compras e likes leem estado e aplicam mudança na mesma transação atômica.",
    severity: "CRITICA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-362",
    applicable: (i) => has(i.payments) || has(i.blockchain),
    exploit: "10 requests simultâneos de compra/saque/decremento causam saldo negativo ou duplicação (double-spending).",
    impact: "Double-spending, estornos duplicados, múltiplas redenções de cupom, perda financeira.",
    mitigation: "Usar transações com SELECT FOR UPDATE ou locks atômicos. Proibir check-then-act sem transação.",
    tests: ["previne race condition em checkout simultâneo", "não permite saldo negativo com requests concorrentes"],
  },
  {
    id: "LAW-9",
    law: "Lei 9: Exposição Mínima de Dados",
    layer: "business",
    title: "Projeção explícita nas queries",
    description:
      "APIs retornam apenas os campos necessários. Proibido retornar objetos completos do banco, hashes, tokens, emails alheios, billing.",
    severity: "ALTA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-200",
    applicable: () => true,
    exploit: "Endpoint retorna o objeto inteiro do banco incluindo password_hash, service_role, ids internos.",
    impact: "Vazamento de credenciais, dados de billing e informações de outros usuários.",
    mitigation: "Select/projection explícita. Serializar com DTO/schema de resposta.",
    tests: ["não expõe campos sensíveis na resposta da API"],
  },
  {
    id: "LAW-10",
    law: "Lei 10: Sanitização de Output (XSS/Injection)",
    layer: "business",
    title: "Escapamento no render e sem innerHTML",
    description:
      "Dados do backend renderizados no frontend são escapados pelo framework. Vetores: dangerouslySetInnerHTML, v-html, innerHTML, eval.",
    severity: "ALTA",
    owasp: "A03 Injection",
    cwe: "CWE-79",
    applicable: () => true,
    exploit: "Injetar <script> ou HTML malicioso em conteúdo renderizado com dangerouslySetInnerHTML.",
    impact: "XSS persistente, roubo de sessão, execução de código no navegador de vítimas.",
    mitigation: "Usar escapamento do framework. Proibir dangerouslySetInnerHTML com dados não sanitizados.",
    tests: ["escapa HTML malicioso no render", "bloqueia uso de dangerouslySetInnerHTML com dados externos"],
  },
  {
    id: "LAW-11",
    law: "Lei 11: Segredos Nunca no Bundle",
    layer: "infrastructure",
    title: "Credenciais em env vars server-side",
    description:
      "Nenhuma chave em código client-side, variáveis NEXT_PUBLIC_, logs, respostas de erro ou arquivos commitados.",
    severity: "CRITICA",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "API key hardcoded no topo de arquivo client-side, .env commitado, service_role exposto ao usuário.",
    impact: "Comprometimento total da conta de serviço, uso indevido de recursos, vazamento de dados.",
    mitigation: "Mover tudo para env vars server-side, rotacionar chaves vazadas, .env no .gitignore.",
    tests: ["nenhum segredo hardcoded no código", "chaves nunca expostas em resposta de erro"],
  },
  {
    id: "LAW-12",
    law: "Lei 12: Upload e SSRF Zero-Trust",
    layer: "infrastructure",
    title: "Magic bytes, reprocessamento e SSRF blocklist",
    description:
      "Upload valida Magic Bytes (não só extensão). Fetch de URLs fornecidas pelo usuário tem allowlist e bloqueia IPs internos.",
    severity: "ALTA",
    owasp: "A10 SSRF",
    cwe: "CWE-918",
    applicable: (i) => has(i.upload) || has(i.webhooks) || has(i.ai),
    exploit: "Upload de polyglot file ou fetch para 169.254.169.254 (metadata cloud) / redes internas.",
    impact: "SSRF: acesso à rede interna e metadados da cloud. Upload de malware/polyglot.",
    mitigation: "Validar magic bytes, reprocessar imagens, bloquear IPs privados/link-local no fetch.",
    tests: ["bloqueia SSRF via proxy para IP interno", "rejeita upload com extensão falsa (magic bytes)"],
  },
  {
    id: "LAW-13",
    law: "Lei 13: Dependency e Supply Chain Awareness",
    layer: "infrastructure",
    title: "Auditoria de dependências e pacotes fantasma",
    description:
      "Avaliar CVEs conhecidas, pacotes abandonados, APIs inseguras (jwt.decode sem verify, bcrypt rounds < 10, yaml.load).",
    severity: "ALTA",
    owasp: "A06 Vulnerable and Outdated Components",
    cwe: "CWE-1104",
    applicable: () => true,
    exploit: "Dependência com CVE conhecido ou pacote fantasma alucinado pelo agente de IA.",
    impact: "Exploração remota conhecida, cadeia de suprimentos comprometida.",
    mitigation: "npm audit/ossf-scorecard, pinar versões, verificar existência de pacotes com context7 antes de usar.",
    tests: ["audita dependências contra CVEs conhecidas", "nenhuma dependência fantasma no package.json"],
  },
  {
    id: "LAW-14",
    law: "Lei 14: Logging Seguro e Observável",
    layer: "infrastructure",
    title: "Erros com contexto, mensagem genérica ao cliente",
    description:
      "Logs de segurança com IP, user agent, userId, timestamp, ação tentada. Ao cliente: mensagem genérica. Nunca logar segredos.",
    severity: "MEDIA",
    owasp: "A09 Logging Failures",
    cwe: "CWE-532",
    applicable: () => true,
    exploit: "Stack trace exposto em produção ou console.log de corpo de request com credenciais.",
    impact: "Vazamento de internals, auxílio a ataque, falhas invisíveis que escondem vulnerabilidades.",
    mitigation: "Log estruturado com contexto; try/catch com logging e re-throw; nunca logar senhas/tokens.",
    tests: ["erro retorna mensagem genérica ao cliente", "stack trace não exposto em produção"],
  },
  {
    id: "LAW-15",
    law: "Lei 15: Configuração Segura por Padrão",
    layer: "infrastructure",
    title: "Security headers, cookies seguros, debug off",
    description:
      "HSTS, X-Content-Type-Options, X-Frame-Options, CSP. Cookies HttpOnly/Secure/SameSite. Debug e source maps off em produção.",
    severity: "ALTA",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-693",
    applicable: () => true,
    exploit: "Clickjacking sem X-Frame-Options, cookie sem HttpOnly, debug habilitado expondo dados.",
    impact: "Clickjacking, roubo de sessão via XSS, exposição de informações de debug.",
    mitigation: "Aplicar headers de segurança, cookies HttpOnly+Secure+SameSite, NODE_ENV=production.",
    tests: ["resposta inclui headers de segurança obrigatórios", "cookie de sessão é HttpOnly e Secure"],
  },
]

const ATTACK_VECTOR_DEFS: CheckDef[] = [
  {
    id: "VECTOR-1",
    law: "Vetor 1: BOLA / IDOR",
    layer: "identity",
    title: "Acesso a recursos por ID mutável",
    description: "Usuário A lê/edita/deleta recursos do usuário B alterando um ID.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-639",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "GET /api/projects/123 alterando para /api/projects/456 (recurso de outro usuário).",
    impact: "Acesso a dados privados de terceiros.",
    mitigation: "Extrair identidade do token e validar ownership em toda leitura.",
    tests: ["rejeita acesso a recurso de outro usuário (IDOR)"],
  },
  {
    id: "VECTOR-2",
    law: "Vetor 2: Broken Access Control",
    layer: "identity",
    title: "Rota protegida acessível sem auth",
    description: "Usuário comum acessa funções de admin/mod; rota protegida sem auth.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-862",
    applicable: (i) => has(i.auth) || has(i.teams) || has(i.multiTenant),
    exploit: "Acessar /api/admin/users sem token ou com token de usuário comum.",
    impact: "Escalação de privilégio administrativo.",
    mitigation: "Guard em cada rota de admin (role) e no middleware de API.",
    tests: ["bloqueia conta comum em rota de admin"],
  },
  {
    id: "VECTOR-3",
    law: "Vetor 3: Race Conditions",
    layer: "business",
    title: "Concorrência em operações de valor",
    description: "Requests simultâneos em compra/saque/like causam saldo negativo ou duplicação.",
    severity: "CRITICA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-362",
    applicable: (i) => has(i.payments) || has(i.blockchain),
    exploit: "Rafael envia 10 POST /api/orders simultâneos com o mesmo saldo.",
    impact: "Double-spending e perda financeira.",
    mitigation: "Transação atômica com lock no registro.",
    tests: ["previne race condition em checkout simultâneo"],
  },
  {
    id: "VECTOR-4",
    law: "Vetor 4: Business Logic Flaws",
    layer: "business",
    title: "Brechas em estorno, cupons, trials e referral",
    description: "Comprar → sacar comissão → reembolsar. Uso infinito de trial.",
    severity: "ALTA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-841",
    applicable: (i) => has(i.payments),
    exploit: "Solicitar reembolso após sacar comissão; reutilizar cupom de 1º uso.",
    impact: "Perda financeira, abuso de promoções.",
    mitigation: "Modelar transições de estado; validar sequência de eventos com idempotência.",
    tests: ["não permite sacar comissão e reembolsar a mesma compra"],
  },
  {
    id: "VECTOR-5",
    law: "Vetor 5: SSRF",
    layer: "infrastructure",
    title: "Fetch server-side de URL arbitrária",
    description: "Proxy/fetch server-side aceita URLs do usuário alcançando rede interna/metadata.",
    severity: "ALTA",
    owasp: "A10 SSRF",
    cwe: "CWE-918",
    applicable: (i) => has(i.upload) || has(i.webhooks) || has(i.ai) || has(i.cms),
    exploit: "POST com url=http://169.254.169.254/latest/meta-data/ em webhook/image proxy.",
    impact: "Acesso a metadados cloud, redes internas e serviços locais.",
    mitigation: "Allowlist de domínios; bloquear IPs privados/link-local.",
    tests: ["bloqueia SSRF via proxy para IP interno"],
  },
  {
    id: "VECTOR-6",
    law: "Vetor 6: Injection",
    layer: "perimeter",
    title: "Concatenação de input em queries/commands",
    description: "SQL/NoSQL/OS/template injection por concatenação.",
    severity: "CRITICA",
    owasp: "A03 Injection",
    cwe: "CWE-89",
    applicable: () => true,
    exploit: "Input com ' OR 1=1-- em query concatenada.",
    impact: "Leitura/escrita não autorizada no banco, execução de comandos.",
    mitigation: "Parameterização obrigatória; ORM com queries preparadas; sem template literals em SQL.",
    tests: ["rejeita payload de SQL injection (OR 1=1)"],
  },
  {
    id: "VECTOR-7",
    law: "Vetor 7: Data Exposure",
    layer: "business",
    title: "Respostas expõem campos sensíveis",
    description: "API retorna hashes, tokens, emails alheios, dados de billing.",
    severity: "ALTA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-200",
    applicable: () => true,
    exploit: "GET /api/user retorna o objeto inteiro do banco.",
    impact: "Vazamento de dados sensíveis.",
    mitigation: "DTO de resposta com projeção explícita.",
    tests: ["não expõe campos sensíveis na resposta da API"],
  },
  {
    id: "VECTOR-8",
    law: "Vetor 8: Auth Bypass",
    layer: "identity",
    title: "Token manipulável ou rota sem verificação",
    description: "Rotas sem token; JWT com algoritmo none/secret fraco.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-287",
    applicable: (i) => has(i.auth) || has(i.sso) || has(i.apiAccess),
    exploit: "Enviar JWT com alg:none ou forjar token com secret conhecido.",
    impact: "Autenticação completamente contornada.",
    mitigation: "jwt.verify com algoritmo e secret fortes; nunca jwt.decode sem verify.",
    tests: ["rejeita token JWT com alg:none"],
  },
  {
    id: "VECTOR-9",
    law: "Vetor 9: Insecure Deserialization",
    layer: "perimeter",
    title: "Payloads desserializados sem schema",
    description: "Objetos do cliente desserializados sem validação de schema.",
    severity: "ALTA",
    owasp: "A08 Deserialization",
    cwe: "CWE-502",
    applicable: () => true,
    exploit: "JSON com protótipo malicioso ou campos inesperados em desserialização.",
    impact: "RCE ou corrupção de dados.",
    mitigation: "Sempre validar com schema (Zod) antes de usar.",
    tests: ["rejeita payload com campos não permitidos (mass assignment)"],
  },
  {
    id: "VECTOR-10",
    law: "Vetor 10: Secrets Leakage",
    layer: "infrastructure",
    title: "Credenciais em código, logs e respostas",
    description: "Segredos em commits, variáveis client-side, logs e respostas de erro.",
    severity: "CRITICA",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "npm install de pacote que lê process.env; .env commitado.",
    impact: "Comprometimento total do serviço.",
    mitigation: "Secrets manager, rotação, scan no CI.",
    tests: ["nenhum segredo hardcoded no código"],
  },
  {
    id: "VECTOR-11",
    law: "Vetor 11: Missing RLS / Tenant Leak",
    layer: "identity",
    title: "Queries sem filtro de ownership/tenant",
    description: "Queries sem filtro de tenant/owner; RLS permissivo.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "SELECT sem WHERE tenant_id em app multi-tenant.",
    impact: "Vazamento cross-tenant completo.",
    mitigation: "Filtro de tenant obrigatório + RLS por auth.uid().",
    tests: ["testes de isolamento entre tenants"],
  },
  {
    id: "VECTOR-12",
    law: "Vetor 12: Phantom Dependencies",
    layer: "infrastructure",
    title: "Pacotes que não existem ou com CVEs",
    description: "Imports de pacotes inexistentes (alucinados) ou versões com CVEs.",
    severity: "ALTA",
    owasp: "A06 Vulnerable and Outdated Components",
    cwe: "CWE-1104",
    applicable: () => true,
    exploit: "Import de pacote fantasma que não está no registry → supply chain.",
    impact: "Build quebrado ou dependência comprometida.",
    mitigation: "Verificar existência e docs reais dos pacotes com context7; npm audit no CI.",
    tests: ["nenhuma dependência fantasma no package.json"],
  },
]

const ANTI_PATTERN_DEFS: CheckDef[] = [
  {
    id: "A1",
    law: "Anti-Padrão A1: Segurança só no cliente",
    layer: "perimeter",
    title: "Auth/validação apenas no frontend",
    description: "Auth checks e validações existem apenas no frontend; o backend aceita qualquer coisa.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-602",
    applicable: () => true,
    exploit: "Chamar a API diretamente (curl) sem passar pelo frontend.",
    impact: "Todas as proteções contornáveis em segundos.",
    mitigation: "Replicar toda validação/autorização no servidor.",
    tests: ["endpoint rejeita chamada direta sem token"],
  },
  {
    id: "A2",
    law: "Anti-Padrão A2: Auth removido para 'resolver bug'",
    layer: "identity",
    title: "requireAuth() removido ou bypassado",
    description: "Middleware de auth, try/catch de verificação de token ou requireAuth removidos para corrigir erro de runtime.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-287",
    applicable: (i) => has(i.auth) || has(i.sso) || has(i.apiAccess),
    exploit: "Endpoint que deveria exigir login aceita requests anônimos após remoção do guard.",
    impact: "Dados de todos os usuários expostos.",
    mitigation: "Nunca remover auth para consertar build; usar mock/teste com token válido.",
    tests: ["deve negar acesso sem token de autenticação"],
  },
  {
    id: "A3",
    law: "Anti-Padrão A3: Secrets hardcoded",
    layer: "infrastructure",
    title: "API keys e service roles no código",
    description: "Chaves diretamente no código-fonte, especialmente em arquivos client-side.",
    severity: "CRITICA",
    owasp: "A02 Cryptographic Failures",
    cwe: "CWE-798",
    applicable: () => true,
    exploit: "GitHub scan de chave commitada.",
    impact: "Conta de serviço comprometida.",
    mitigation: "Env vars server-side + rotação + scan de segredos no CI.",
    tests: ["nenhum segredo hardcoded no código"],
  },
  {
    id: "A4",
    law: "Anti-Padrão A4: RLS desabilitado",
    layer: "identity",
    title: "RLS disabled ou policy USING (true)",
    description: "ALTER TABLE DISABLE ROW LEVEL SECURITY ou policies USING (true) para 'fazer funcionar'.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-284",
    applicable: (i) => has(i.multiTenant) || has(i.teams) || has(i.auth),
    exploit: "Query retorna dados de todos os tenants.",
    impact: "Vazamento total de dados.",
    mitigation: "Reabilitar RLS; policies por auth.uid(); testes de isolamento no CI.",
    tests: ["policy RLS restringe por auth.uid()"],
  },
  {
    id: "A5",
    law: "Anti-Padrão A5: Middleware fantasma",
    layer: "perimeter",
    title: "Rate limiter/CORS/CSRF importados mas nunca montados",
    description: "Proteções configuradas mas nunca registradas com app.use() ou equivalente.",
    severity: "ALTA",
    owasp: "A05 Security Misconfiguration",
    cwe: "CWE-1188",
    applicable: () => true,
    exploit: "Endpoint sem rate limit/CORS porque o middleware não foi montado.",
    impact: "Abuso de endpoint, DoS, CORS aberto.",
    mitigation: "Teste que verifica middleware montado nas rotas.",
    tests: ["middleware de segurança montado nas rotas críticas"],
  },
  {
    id: "A6",
    law: "Anti-Padrão A6: Error swallowing",
    layer: "infrastructure",
    title: "catch vazio ou console.log sem tratamento",
    description: "catch (e) {} ou console.log(e) sem re-throw/logging adequado. Falhas invisíveis.",
    severity: "MEDIA",
    owasp: "A09 Logging Failures",
    cwe: "CWE-390",
    applicable: () => true,
    exploit: "Erro de autorização silenciado esconde acesso indevido tentado.",
    impact: "Vulnerabilidades invisíveis em produção.",
    mitigation: "Log estruturado com contexto e re-throw quando necessário.",
    tests: ["erro retorna mensagem genérica ao cliente"],
  },
  {
    id: "A7",
    law: "Anti-Padrão A7: Permissões excessivas",
    layer: "identity",
    title: "Service role no lugar de anon key; tokens sem expiração",
    description: "Service role keys onde anon bastaria; IAM com *; tokens sem expiração.",
    severity: "ALTA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-276",
    applicable: (i) => has(i.auth) || has(i.apiAccess) || has(i.payments),
    exploit: "Service role key usada no client expõe banco inteiro.",
    impact: "Acesso irrestrito a dados.",
    mitigation: "Least privilege: anon key no cliente, service role só no servidor.",
    tests: ["service role key nunca exposta ao cliente"],
  },
  {
    id: "A8",
    law: "Anti-Padrão A8: Validação ausente em Server Actions",
    layer: "perimeter",
    title: "Server Actions/API Routes sem validação",
    description: "Next.js Server Actions, Remix/SvelteKit actions sem validação de input (confia no FormData bruto).",
    severity: "ALTA",
    owasp: "A03 Injection",
    cwe: "CWE-20",
    applicable: () => true,
    exploit: "Server Action aceita FormData manipulada com campos extras.",
    impact: "Mass assignment e dados corrompidos.",
    mitigation: "Validar todo FormData com schema antes de usar.",
    tests: ["Server Action rejeita payload com campos não permitidos"],
  },
  {
    id: "A9",
    law: "Anti-Padrão A9: Exposição de admin por default",
    layer: "identity",
    title: "Painéis admin/console acessíveis sem auth",
    description: "Rotas /api/admin/* e consoles de debug acessíveis sem autenticação em produção.",
    severity: "CRITICA",
    owasp: "A01 Broken Access Control",
    cwe: "CWE-552",
    applicable: () => true,
    exploit: "Acessar /api/admin/dashboard diretamente.",
    impact: "Controle total da aplicação.",
    mitigation: "Proteger rotas de admin com role + auth por padrão.",
    tests: ["rota de admin exige role administrativa"],
  },
  {
    id: "A10",
    law: "Anti-Padrão A10: Paginação sem limite",
    layer: "perimeter",
    title: "SELECT * ou listagem sem LIMIT",
    description: "Queries de listagem sem LIMIT permitem dump completo via ?pageSize=999999.",
    severity: "ALTA",
    owasp: "A04 Insecure Design",
    cwe: "CWE-770",
    applicable: () => true,
    exploit: "GET /api/items?pageSize=999999 retorna todo o banco.",
    impact: "Dump completo do banco.",
    mitigation: "Limite máximo de pageSize e default pequeno.",
    tests: ["impede dump completo via paginação sem limite"],
  },
]

const severityScore: Record<SecuritySeverity, number> = {
  CRITICA: 25,
  ALTA: 15,
  MEDIA: 8,
  BAIXA: 3,
}

function evaluate(defs: CheckDef[], input: Partial<ProjectInput>): SecurityCheck[] {
  return defs.map((d) => ({
    id: d.id,
    law: d.law,
    layer: d.layer,
    title: d.title,
    description: d.description,
    severity: d.severity,
    owasp: d.owasp,
    cwe: d.cwe,
    applicable: d.applicable(input),
    exploit: d.exploit,
    impact: d.impact,
    mitigation: d.mitigation,
    tests: d.tests,
  }))
}

function gradeFor(score: number): SecurityAuditResult["scorecard"]["grade"] {
  if (score >= 85) return "A"
  if (score >= 70) return "B"
  if (score >= 55) return "C"
  if (score >= 40) return "D"
  return "F"
}

export function runSecurityAudit(input: Partial<ProjectInput>): SecurityAuditResult {
  const laws = evaluate(LAW_DEFS, input)
  const attackVectors = evaluate(ATTACK_VECTOR_DEFS, input)
  const antiPatterns = evaluate(ANTI_PATTERN_DEFS, input)

  const applicable = [...laws, ...attackVectors, ...antiPatterns].filter((c) => c.applicable)
  const critical = applicable.filter((c) => c.severity === "CRITICA").length
  const high = applicable.filter((c) => c.severity === "ALTA").length
  const medium = applicable.filter((c) => c.severity === "MEDIA").length
  const low = applicable.filter((c) => c.severity === "BAIXA").length

  const vibeAntiPatterns = antiPatterns.map((c) => c.id)
  const score = Math.max(
    0,
    100 -
      applicable.reduce((acc, c) => acc + severityScore[c.severity], 0),
  )

  const ordered = [...applicable].sort(
    (a, b) => severityScore[b.severity] - severityScore[a.severity],
  )
  const topActions = ordered.slice(0, 3).map(
    (c) => `[${c.severity}] ${c.id} — ${c.title}: ${c.mitigation}`,
  )

  const redTeam = applicable
    .filter((c) => c.severity === "CRITICA" || c.severity === "ALTA")
    .map((c) => `[${c.id}] ${c.exploit}`)
  const blueTeam = applicable.map((c) => `[${c.id}] ${c.mitigation}`)
  const securityTests = Array.from(
    new Set(applicable.flatMap((c) => c.tests)),
  ).map((t) => `test("VULN-${applicable.findIndex((c) => c.tests.includes(t)) + 1}: ${t}")`)

  return {
    target: input.description ? `${input.domain} — ${input.description.slice(0, 80)}` : `${input.domain}`,
    laws,
    attackVectors,
    antiPatterns,
    scorecard: {
      critical,
      high,
      medium,
      low,
      vibeAntiPatterns,
      grade: gradeFor(score),
      summary: `${critical} críticas, ${high} altas, ${medium} médias, ${low} baixas — nota ${gradeFor(score)}`,
    },
    topActions,
    redTeam,
    blueTeam,
    securityTests,
  }
}
