// Gera o motor embarcado da skill: copia src/ e templates/ para dentro de
// skills/onp-spec-driven/scripts/ e escreve o entrypoint.
//
// The skill is SELF-CONTAINED: copying the skills/onp-spec-driven folder to
// .claude/skills/ IS the entire install (no npm, no npx, no global CLI).
// test/skill-sync.test.js falha se scripts/ divergir do que este build gera.

import { cpSync, rmSync, mkdirSync, writeFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS = [
  'onp-spec-driven',
  'onp-spec-driven-antigravity',
  'onp-spec-driven-codex',
  'onp-spec-driven-cursor',
  'onp-spec-driven-opencode',
];
export const ENTRY = `#!/usr/bin/env node
// Entrypoint of the onp-spec-driven skill's embedded engine.
// Usage (from the ROOT of the user's project):
//   node <skill-dir>/scripts/onp-spec.mjs <command> [options]
// Generated by tools/build-skill.mjs — do not edit by hand; edit src/ and regenerate.
import { run } from './lib/src/cli.js';

run(process.argv.slice(2)).then(
  (code) => {
    process.exitCode = code;
  },
  (err) => {
    console.error(\`error: \${err.message}\`);
    process.exitCode = 2;
  }
);
`;

export function buildSkillDir(scriptsDir) {
  rmSync(scriptsDir, { recursive: true, force: true });
  mkdirSync(path.join(scriptsDir, 'lib'), { recursive: true });
  cpSync(path.join(ROOT, 'src'), path.join(scriptsDir, 'lib', 'src'), { recursive: true });
  cpSync(path.join(ROOT, 'templates'), path.join(scriptsDir, 'lib', 'templates'), {
    recursive: true,
    filter: (src) => !src.includes(`${path.sep}agents`),
  });
  writeFileSync(path.join(scriptsDir, 'onp-spec.mjs'), ENTRY);
  return scriptsDir;
}

export function buildSkill() {
  return SKILLS.map((skill) => buildSkillDir(path.join(ROOT, 'skills', skill, 'scripts')));
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const outs = buildSkill();
  for (const out of outs) {
    console.log(`✔ embedded engine generated at ${path.relative(ROOT, out)}/`);
  }
}
