// Ensures the engine embedded in EACH skill (claude, antigravity, codex and
// cursor) stays in sync with src/ and templates/ — kills silent drift
// (SK-5). If this test fails: node tools/build-skill.mjs

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync, existsSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { ENTRY } from '../tools/build-skill.mjs';

const ROOT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const SKILLS = [
  'onp-spec-driven',
  'onp-spec-driven-antigravity',
  'onp-spec-driven-codex',
  'onp-spec-driven-cursor',
  'onp-spec-driven-opencode',
];

function walk(dir, base = dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    if (e.name === '.DS_Store') continue;
    const full = path.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(full, base));
    else out.push(path.relative(base, full));
  }
  return out.sort();
}

for (const skill of SKILLS) {
  const SCRIPTS = path.join(ROOT, 'skills', skill, 'scripts');

  test(`[${skill}] embedded engine exists (run: node tools/build-skill.mjs)`, () => {
    assert.ok(existsSync(SCRIPTS), `skills/${skill}/scripts/ does not exist`);
  });

  test(`[${skill}] scripts/lib/src mirrors src/ byte for byte`, () => {
    const srcFiles = walk(path.join(ROOT, 'src'));
    const libFiles = walk(path.join(SCRIPTS, 'lib', 'src'));
    assert.deepEqual(libFiles, srcFiles, 'file list diverges — regenerate the build');
    for (const rel of srcFiles) {
      assert.equal(
        readFileSync(path.join(SCRIPTS, 'lib', 'src', rel), 'utf-8'),
        readFileSync(path.join(ROOT, 'src', rel), 'utf-8'),
        `content diverges: ${rel} — run node tools/build-skill.mjs`
      );
    }
  });

  test(`[${skill}] scripts/lib/templates mirrors templates/ (without agents/)`, () => {
    const tplFiles = walk(path.join(ROOT, 'templates')).filter((f) => !f.startsWith('agents/'));
    const libFiles = walk(path.join(SCRIPTS, 'lib', 'templates'));
    assert.deepEqual(libFiles, tplFiles);
    for (const rel of tplFiles) {
      assert.equal(
        readFileSync(path.join(SCRIPTS, 'lib', 'templates', rel), 'utf-8'),
        readFileSync(path.join(ROOT, 'templates', rel), 'utf-8'),
        `template diverges: ${rel}`
      );
    }
  });

  test(`[${skill}] entrypoint onp-spec.mjs is the one generated by the build`, () => {
    assert.equal(readFileSync(path.join(SCRIPTS, 'onp-spec.mjs'), 'utf-8'), ENTRY);
  });
}

// Each skill's SKILL.md declares its agent (init uses the marker to avoid
// installing the wrong skill) and all keep the SAME version (policy: bump together).
test('SKILL.md: correct agent marker and aligned versions', () => {
  const frontmatter = (skill) =>
    readFileSync(path.join(ROOT, 'skills', skill, 'SKILL.md'), 'utf-8').split('---')[1];
  const claude = frontmatter('onp-spec-driven');
  const ag = frontmatter('onp-spec-driven-antigravity');
  const codex = frontmatter('onp-spec-driven-codex');
  const cursor = frontmatter('onp-spec-driven-cursor');
  const opencode = frontmatter('onp-spec-driven-opencode');
  assert.match(claude, /^\s*agent:\s*claude\s*$/m);
  assert.match(ag, /^\s*agent:\s*antigravity\s*$/m);
  assert.match(codex, /^\s*agent:\s*codex\s*$/m);
  assert.match(cursor, /^\s*agent:\s*cursor\s*$/m);
  assert.match(opencode, /^\s*agent:\s*opencode\s*$/m);
  const versao = (fm) => fm.match(/^\s*version:\s*(\S+)/m)?.[1];
  assert.equal(versao(claude), versao(ag), 'skill versions diverge — bump together');
  assert.equal(versao(claude), versao(codex), 'skill versions diverge — bump together');
  assert.equal(versao(claude), versao(cursor), 'skill versions diverge — bump together');
  assert.equal(versao(claude), versao(opencode), 'skill versions diverge — bump together');
});

// Cursor requires the frontmatter `name:` to EQUAL the installed folder name
// (.cursor/skills/onp-spec-driven) — otherwise the skill does not load.
test('SKILL.md (cursor): name compatible with the installation folder', () => {
  const frontmatter = readFileSync(
    path.join(ROOT, 'skills', 'onp-spec-driven-cursor', 'SKILL.md'),
    'utf-8'
  ).split('---')[1];
  assert.match(frontmatter, /^\s*name:\s*onp-spec-driven\s*$/m);
  assert.match(frontmatter, /^\s*description:\s*\S/m, 'description is required for automatic activation');
});

// The anti-fraud rules of the contract are sacred: no skill can lose
// "never weaken/skip/delete a test" nor the graceful degradation (WEAK PROOF).
test('SKILL.md: contract and graceful degradation present in all four skills', () => {
  for (const skill of SKILLS) {
    const conteudo = readFileSync(path.join(ROOT, 'skills', skill, 'SKILL.md'), 'utf-8');
    assert.match(conteudo, /Never weaken, skip or delete a test/, `${skill}: contract rule 6 is missing`);
    assert.match(conteudo, /skip\/todo\) is not proof/, `${skill}: "skip is not proof" is missing`);
    assert.match(conteudo, /WEAK PROOF \(manual audit\)/, `${skill}: graceful degradation is missing`);
    assert.match(conteudo, /audit --ci` exits with code 0/, `${skill}: audit gate is missing`);
  }
});

// On codex and opencode, cost is the user's choice: the skill can NEVER lose
// the gate of confirming models/efforts before executing (a cheap license
// burns tokens with a strong model + high effort).
test('SKILL.md (codex/opencode): model and effort confirmation gate present', () => {
  for (const skill of ['onp-spec-driven-codex', 'onp-spec-driven-opencode']) {
    const conteudo = readFileSync(path.join(ROOT, 'skills', skill, 'SKILL.md'), 'utf-8');
    assert.match(conteudo, /MODEL and EFFORT are the USER's choice — confirm BEFORE\s+executing/);
    assert.match(conteudo, /Without this confirmation,\s+do not execute/);
    assert.match(conteudo, /Never\s+raise model\/effort without the user asking/);
    assert.match(conteudo, /--modelo .* --esforco baixo/);
    assert.match(conteudo, /onp-spec tarefa <feature> <T-xxx> --modelo/);
  }
});

// On cursor, same: claude-*/gpt-* models are billed per use on the user's
// plan — the model confirmation gate is sacred, and the skill needs to be
// honest about effort (there is no CLI flag; it goes in the slug).
test('SKILL.md (cursor): model confirmation gate and effort honesty', () => {
  const conteudo = readFileSync(path.join(ROOT, 'skills', 'onp-spec-driven-cursor', 'SKILL.md'), 'utf-8');
  assert.match(conteudo, /The MODEL of each task is the USER's choice — confirm BEFORE\s+executing/);
  assert.match(conteudo, /Without this confirmation,\s+do not execute/);
  assert.match(conteudo, /Never swap a model for a\s+more expensive one without the user asking/);
  assert.match(conteudo, /--modelo composer/);
  assert.match(conteudo, /onp-spec tarefa <feature> <T-xxx> --modelo/);
  // honesty: the Cursor CLI has no effort flag — the slug decides
  assert.match(conteudo, /the Cursor CLI has no effort flag/);
  assert.match(conteudo, /gpt-5\.6-terra-high/);
  // and the executor depends on --force (without it, print mode doesn't write)
  assert.match(conteudo, /--force/);
  assert.match(conteudo, /\.cursor\/cli\.json/);
});
