// scaffold — the DoD is born executable.
// For every AC without an annotated test, generates a test skeleton that FAILS
// until implemented. The title carries @spec:AC-xxx; the body carries the
// Given/When/Then from the spec as a script.

import { writeFileSync, mkdirSync, existsSync } from 'fs';
import path from 'path';
import { allAcs } from '../parsers/spec.js';

function detectStyle(config) {
  const cmd = config.testCommand || '';
  if (cmd.includes('vitest')) return 'vitest';
  if (cmd.includes('jest')) return 'jest';
  if (cmd.includes('pytest')) return 'pytest';
  return 'node';
}

function jsHeader(style) {
  if (style === 'vitest') {
    return `import { test } from 'vitest';\n`;
  }
  if (style === 'jest') {
    return '';
  }
  return `import { test } from 'node:test';\nimport assert from 'node:assert/strict';\n`;
}

function jsFail(style, message) {
  if (style === 'vitest' || style === 'jest') {
    return `  throw new Error('${message}');`;
  }
  return `  assert.fail('${message}');`;
}

function renderJsTest(style, story, ac) {
  const lines = [];
  lines.push(`// ${story.id} — ${story.title}`);
  lines.push(`test('${ac.id}: ${ac.title.replace(/'/g, "\\'")} @spec:${ac.id}', () => {`);
  for (const g of ac.given) lines.push(`  // Given: ${g}`);
  for (const w of ac.when) lines.push(`  // When: ${w}`);
  for (const t of ac.then) lines.push(`  // Then: ${t}`);
  lines.push(jsFail(style, `acceptance criterion ${ac.id} not yet proven — implement this test`));
  lines.push('});');
  return lines.join('\n');
}

function renderPyTest(story, ac) {
  const fn = ac.id.toLowerCase().replace(/-/g, '_');
  const lines = [];
  lines.push(`# ${story.id} — ${story.title}`);
  lines.push(`def test_${fn}():`);
  lines.push(`    """${ac.id}: ${ac.title} @spec:${ac.id}"""`);
  for (const g of ac.given) lines.push(`    # Given: ${g}`);
  for (const w of ac.when) lines.push(`    # When: ${w}`);
  for (const t of ac.then) lines.push(`    # Then: ${t}`);
  lines.push(`    raise AssertionError("acceptance criterion ${ac.id} not yet proven — implement this test")`);
  return lines.join('\n');
}

export function scaffoldTests(project, featureName, { force = false } = {}) {
  const { config } = project;
  const feature = project.features.find((f) => f.name === featureName);
  if (!feature?.spec) {
    throw new Error(`feature "${featureName}" not found or has no spec.md`);
  }

  const testFileSet = new Set(project.testFiles);
  const tagged = new Set(
    project.annotations.specTags.filter((t) => testFileSet.has(t.file)).map((t) => t.acId)
  );

  const style = detectStyle(config);
  const ext = style === 'pytest' ? 'py' : 'js';
  const fileName =
    style === 'pytest' ? `test_spec_${featureName.replace(/-/g, '_')}.py` : `${featureName}.spec.test.${ext}`;
  const outDir = path.join(config.rootDir, style === 'pytest' ? 'tests' : 'test');
  const outPath = path.join(outDir, fileName);

  const pending = [];
  for (const story of feature.spec.stories) {
    for (const ac of story.acs) {
      if (!tagged.has(ac.id)) pending.push({ story, ac });
    }
  }

  // principles [MUST]/[SHOULD] with test verification not tagged yet:
  // the skeleton is generated alongside — otherwise the gate demands a test no step creates
  const taggedPrinciples = new Set(
    project.annotations.principleTags.filter((t) => testFileSet.has(t.file)).map((t) => t.principleId)
  );
  const pendingPrinciples = [];
  for (const p of project.constitution?.principles || []) {
    for (const check of p.checks) {
      if (check.kind === 'test' && !taggedPrinciples.has(check.principleTag)) {
        pendingPrinciples.push({ principle: p, tag: check.principleTag });
      }
    }
  }

  if (pending.length === 0 && pendingPrinciples.length === 0) {
    return { created: null, pending: 0, message: 'all acceptance criteria (and principles) already have an annotated test' };
  }
  if (existsSync(outPath) && !force) {
    throw new Error(
      `${path.relative(config.rootDir, outPath)} already exists — use --force to overwrite or annotate the existing tests`
    );
  }

  let content;
  if (style === 'pytest') {
    content = `# Spec tests for feature ${featureName} — generated by onp-spec scaffold\n\n`;
    content += pending.map(({ story, ac }) => renderPyTest(story, ac)).join('\n\n');
    content += pendingPrinciples
      .map(({ principle, tag }) => `\n\n${renderPyPrinciple(principle, tag)}`)
      .join('');
    content += '\n';
  } else {
    content = `// Spec tests for feature ${featureName} — generated by onp-spec scaffold\n${jsHeader(style)}\n`;
    content += pending.map(({ story, ac }) => renderJsTest(style, story, ac)).join('\n\n');
    content += pendingPrinciples
      .map(({ principle, tag }) => `\n\n${renderJsPrinciple(style, principle, tag)}`)
      .join('');
    content += '\n';
  }

  mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, content);

  return {
    created: path.relative(config.rootDir, outPath),
    pending: pending.length + pendingPrinciples.length,
    acIds: [
      ...pending.map((p) => p.ac.id),
      ...pendingPrinciples.map((p) => p.tag),
    ],
  };
}

function renderJsPrinciple(style, principle, tag) {
  const lines = [];
  lines.push(`// ${principle.id} [${principle.level}] — ${principle.title}`);
  lines.push(
    `test('${principle.id}: ${principle.title.replace(/'/g, "\\'")} @principle:${tag}', () => {`
  );
  lines.push(jsFail(style, `principle ${principle.id} not yet proven — implement this test`));
  lines.push('});');
  return lines.join('\n');
}

function renderPyPrinciple(principle, tag) {
  const fn = tag.toLowerCase().replace(/-/g, '_');
  const lines = [];
  lines.push(`# ${principle.id} [${principle.level}] — ${principle.title}`);
  lines.push(`def test_${fn}():`);
  lines.push(`    """${principle.id}: ${principle.title} @principle:${tag}"""`);
  lines.push(`    raise AssertionError("principle ${principle.id} not yet proven — implement this test")`);
  return lines.join('\n');
}
