#!/usr/bin/env node
// Entrypoint of the onp-spec-driven skill's embedded engine.
// Usage (from the ROOT of the user's project):
//   node <skill-dir>/scripts/onp-spec.mjs <command> [options]
// Generated by tools/build-skill.mjs — do not edit by hand; edit src/ and regenerate.
import { run } from './lib/src/cli.js';

run(process.argv.slice(2)).then(
  (code) => {
    process.exitCode = code;
  },
  (err) => {
    console.error(`error: ${err.message}`);
    process.exitCode = 2;
  }
);
