name: Deploy Site

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "apps/site/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      - uses: pnpm/action-setup@f40ffcd9367d9f12939873eb1018b921a783ffaa
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install
      - run: pnpm turbo build --filter=@ade/site
      - uses: amondnet/vercel-action@de09aeac2ace6599ec9b11ef87558759a496bac4
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          working-directory: apps/site
          vercel-version: latest
